
## what perpose of configmap is used hear?
## configmap is used to store configuration data that can be consumed by pods.

apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: kubernates-dashboard
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: kubernates-dashboard
  # these are replica set labels
  labels:
    project: TailorSpot
    component: catalogue
    tier: backend
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: TailorSpot
      component: catalogue
      tier: backend
  # pod definition
  template:
    metadata:
      labels:
        project: TailorSpot
        component: catalogue
        tier: backend
    spec:
      containers:
      - name: catalogue
        image: paulmaruthi18/catalogue:v1
        imagePullPolicy: Always    ## Always pull the image from the registry, even if it is already present on the node.
        envFrom:
        - configMapRef:
            name: catalogue
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15

---
apiVersion: apps/v1
kind: Service
metadata:
  name: catalogue
  namespace: kubernates-dashboard
spec:
  selector:
    project: TailorSpot
    component: catalogue
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port


### why we are using service here is to expose the deployment to other deployments in the cluster. (catlog to mongodb) 
##  we can also use ingress to expose the deployment to outside world. 
## but we are not using ingress here because we are using kubernates-dashboard which is a web UI for kubernates. 
## so we are using service to expose the deployment to kubernates-dashboard.

