apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  namespace: roboshop
spec:
  containers:
    - name: volume-container
      image: nginx:latest
      volumeMounts:
      - name: volume-mount
        mountPath: /usr/share/nginx/html
  volumes:
    - name: volume-mount
      persistentVolumeClaim:
        claimName: volume-pvc
