apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
  namespace: default
spec:
  containers:
  - name: empty-dir-container
    image: nginx:latest
    volumeMounts:
    - name: empty-dir-volume
      mountPath: /var/log/nginx
      command: ["sleep", "100"]

  - name: almalinux-container
    image: almalinux:latest
    volumeMounts:
    - name: empty-dir-volume
      mountPath: /var/log/almalinux
      readOnly: true
  volumes:
  - name: empty-dir-volume
    emptyDir: {}  