apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
spec:
  containers:
    - name: empty-dir-container
      image: nginx:latest
      volumeMounts:
        - name: empty-dir-volume
          mountPath: /var/log/nginx

    - name: almalinux-container
      image: almalinux:latest
      command:
        - sleep
        - "100"
      volumeMounts:
        - name: empty-dir-volume
          mountPath: /var/log/almalinux
          readOnly: true

  volumes:
    - name: empty-dir-volume
      emptyDir: {}