apiVersion: v1
kind: Pod
metadata:
  name: 
  
spec:
  containers:
    - name: empty-dir-container
      image: nginx:latest
      volumeMounts:
        - name: empty-dir-volume
          mountPath: /var/log/nginx

    - name: almalinux-container
      image: almalinux:latest
      command:
        - sleep
        - "100"
      volumeMounts:
        - name: empty-dir-volume
          mountPath: /var/log/almalinux
          readOnly: true

  volumes:
    - name: empty-dir-volume
      emptyDir: {}

  ## step:1 kubectl apply -f 02-volumeEmptyDir.yaml
  ## step:2 kubectl exec -it empty-dir-pod -c almalinux-container -- bash



  ### why this error comming means if pod is already created and you are trying to update the pod then it will not allow to update 
  ## so need to delete the pod and create again with new changes. 

  ## ERRROR:
  ##The Pod "empty-dir-pod" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)

